CREATE TABLE users (
userid SERIAL NOT NULL PRIMARY KEY,
fname VARCHAR(100) NOT NULL,
lname VARCHAR(100) NOT NULL,
uname VARCHAR(100) NOT NULL
);

CREATE TABLE recipes (
recipeid SERIAL NOT NULL PRIMARY KEY,
userid INT NOT NULL REFERENCES users(userid),
recipename VARCHAR(150) NOT NULL,
recipedesc VARCHAR(10485760) NOT NULL
);

CREATE TABLE log (
logid SERIAL NOT NULL PRIMARY KEY,
recipeid INT REFERENCES recipes(recipeid),
datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);